name: Release

on:
  workflow_run:
    workflows: ["Publish"]
    types: [completed]

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - uses: denoland/setup-deno@v1
        with:
          deno-version: rc
      - run: deno task client_emit
      - uses: little-core-labs/get-git-tag@v3.0.2
        id: tagName
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "client.js"
          generateReleaseNotes: true
          tag: ${{ steps.tagName.outputs.tag }}