name: Release

on:
  workflow_run:
    workflows: ["Publish"]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - uses: denoland/setup-deno@v1
        with:
          deno-version: rc
      - run: deno task client_emit
      - run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> "$GITHUB_ENV"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "client.js"
          generateReleaseNotes: true
          tag: "$GIT_TAG"