name: Release

on:
  workflow_run:
    workflows: ["Publish"]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: rc
      - run: deno task client_emit
      - run: echo ::set-output name=current_tag::"echo $(git describe --tags --abbrev=0)"
        id: tag
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "client.js"
          generateReleaseNotes: true
          tag: ${{ steps.tag.outputs.current_tag }}