name: Test

on: 
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: rc
      - run: deno task test
        env:
          EVERHOUR_API_KEY: ${{ secrets.EVERHOUR_API_KEY }}